apiVersion: sql.arcdata.microsoft.com/v1alpha1
kind: sqlmanagedinstance
metadata:
  name: test3
  namespace: arc
spec:
  limits:
    vcores: 5
  requests:
    vcores: 2
  service:
    type: NodePort
  storage:
    data:
      className: default
      size: 5Gi
    logs:
      className: default
      size: 5Gi