apiVersion: sql.arcdata.microsoft.com/v1alpha1
kind: sqlmanagedinstance
metadata:
  name: test4
  namespace: arc
spec:
  limits:
    vcores: 4
  requests:
    vcores: 2
  service:
    type: LoadBalancer
  storage:
    data:
      className: default
      size: 5Gi
    logs:
      className: default
      size: 5Gi