apiVersion: v1
data:
  mssql-sa-password: U2VhdHRsZTgwMA==
  username: c2E=
kind: Secret
metadata:
  name: test6-login-secret
  namespace: arc
type: Opaque
---
apiVersion: sql.arcdata.microsoft.com/v1alpha1
kind: sqlmanagedinstance
metadata:
  name: test6
  namespace: arc
spec:
  limits:
    vcores: 4
  requests:
    vcores: 2
  service:
    type: LoadBalancer
  storage:
    data:
      className: default
      size: 5Gi
    logs:
      className: default
      size: 5Gi